/********************************************************************
* SAK_d.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SAK_d.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSAK_d();
extern void G__cpp_setup_inheritanceSAK_d();
extern void G__cpp_setup_typetableSAK_d();
extern void G__cpp_setup_memvarSAK_d();
extern void G__cpp_setup_globalSAK_d();
extern void G__cpp_setup_memfuncSAK_d();
extern void G__cpp_setup_funcSAK_d();
extern void G__set_cpp_environmentSAK_d();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sak_Gates.hpp"
#include "sak_Histograms.hpp"
#include "sak_Canvas.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SAK_dLN_TClass;
extern G__linked_taginfo G__SAK_dLN_TBuffer;
extern G__linked_taginfo G__SAK_dLN_TDirectory;
extern G__linked_taginfo G__SAK_dLN_TMemberInspector;
extern G__linked_taginfo G__SAK_dLN_TObject;
extern G__linked_taginfo G__SAK_dLN_TNamed;
extern G__linked_taginfo G__SAK_dLN_TString;
extern G__linked_taginfo G__SAK_dLN_string;
extern G__linked_taginfo G__SAK_dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SAK_dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SAK_dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SAK_dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SAK_dLN_TAttLine;
extern G__linked_taginfo G__SAK_dLN_TAttFill;
extern G__linked_taginfo G__SAK_dLN_TAttMarker;
extern G__linked_taginfo G__SAK_dLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SAK_dLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SAK_dLN_TH1;
extern G__linked_taginfo G__SAK_dLN_TGraph;
extern G__linked_taginfo G__SAK_dLN_TH2;
extern G__linked_taginfo G__SAK_dLN_TCutG;
extern G__linked_taginfo G__SAK_dLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SAK_dLN_TFile;
extern G__linked_taginfo G__SAK_dLN_TDirectoryFile;
extern G__linked_taginfo G__SAK_dLN_sak;
extern G__linked_taginfo G__SAK_dLN_sakcLcLGate;
extern G__linked_taginfo G__SAK_dLN_vectorlEsakcLcLGatecOallocatorlEsakcLcLGategRsPgR;
extern G__linked_taginfo G__SAK_dLN_vectorlEsakcLcLGatecOallocatorlEsakcLcLGategRsPgRcLcLiterator;
extern G__linked_taginfo G__SAK_dLN_reverse_iteratorlEvectorlEsakcLcLGatecOallocatorlEsakcLcLGategRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SAK_dLN_sakcLcLLoadCuts;
extern G__linked_taginfo G__SAK_dLN_sakcLcLSaveCuts;
extern G__linked_taginfo G__SAK_dLN_TArray;
extern G__linked_taginfo G__SAK_dLN_TArrayD;
extern G__linked_taginfo G__SAK_dLN_TH1D;
extern G__linked_taginfo G__SAK_dLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SAK_dLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SAK_dLN_TH2D;
extern G__linked_taginfo G__SAK_dLN_sakcLcLHistogram2D;
extern G__linked_taginfo G__SAK_dLN_sakcLcLHistogram1D;
extern G__linked_taginfo G__SAK_dLN_TCanvas;
extern G__linked_taginfo G__SAK_dLN_TPad;

/* STUB derived class for protected member access */
