/********************************************************************
* RNRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RNRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRNRootDict();
extern void G__cpp_setup_inheritanceRNRootDict();
extern void G__cpp_setup_typetableRNRootDict();
extern void G__cpp_setup_memvarRNRootDict();
extern void G__cpp_setup_globalRNRootDict();
extern void G__cpp_setup_memfuncRNRootDict();
extern void G__cpp_setup_funcRNRootDict();
extern void G__set_cpp_environmentRNRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RNUnpack2Root.hpp"
#include "sakReadBuffer.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RNRootDictLN_TClass;
extern G__linked_taginfo G__RNRootDictLN_TBuffer;
extern G__linked_taginfo G__RNRootDictLN_TMemberInspector;
extern G__linked_taginfo G__RNRootDictLN_TObject;
extern G__linked_taginfo G__RNRootDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__RNRootDictLN_string;
extern G__linked_taginfo G__RNRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RNRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RNRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RNRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RNRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RNRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RNRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RNRootDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__RNRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RNRootDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__RNRootDictLN_sak;
extern G__linked_taginfo G__RNRootDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RNRootDictLN_RN_module;
extern G__linked_taginfo G__RNRootDictLN_RNUnpack2Root;
extern G__linked_taginfo G__RNRootDictLN_vectorlERN_modulecOallocatorlERN_modulegRsPgR;
extern G__linked_taginfo G__RNRootDictLN_vectorlERN_modulecOallocatorlERN_modulegRsPgRcLcLiterator;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlERN_modulecOallocatorlERN_modulegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RNRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__RNRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<RN_module,allocator<RN_module> > G__vectorlERN_modulecOallocatorlERN_modulegRsPgR;
